#!/usr/bin/python
# coding=utf-8

"""Defines the custom callbacks used at train time."""

import tensorflow as tf


class SaveImageToDisk(tf.keras.callbacks.Callback):
    """
    This callback saves to disk an image generated by generator.

    Serves as visual performance proof of the model
    """
    def __init__(self, path):
        """
        Init the callback.

        Args:
            path (str): folder where the results will be saved
        """
        self.path = path

    def on_epoch_end(self, epoch, logs=None):
        pass

    def on_train_begin(self, logs=None):
        pass